function yfit = ...
    crossfun(xtrain,ytrain,xtest,rbf_sigma,boxconstraint)
% Train the model on xtrain, ytrain, 
% and get predictions of class of xtest
options = statset('MaxIter',Inf);
svmStruct = svmtrain(xtrain,ytrain,'autoscale',false,...
    'Kernel_Function','rbf',...
   'rbf_sigma',rbf_sigma,...
   'boxconstraint',boxconstraint,...
   'options',options);
yfit = svmclassify(svmStruct,xtest);